sudo: required

git:
  depth: 1

services:
  - docker

script:
  - make --no-builtin-rules build
  - make --no-builtin-rules test

deploy:
  provider: script
  script: 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make push;'
  on:
    branch: master
