sudo: required
dist: xenial

services:
  - docker

script:
  - make build
  - make test
  - [ "$TRAVIS_PULL_REQUEST" = "false" ] && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - [ "$TRAVIS_PULL_REQUEST" = "false" ] && make push
